import { Divider, Grid } from '@mui/material';
import { Box } from '@mui/system';
import Head from 'next/head';
import LatestArticles from '../../components/blog/LatestArticles';
import PopularPosts from '../../components/blog/PopularPosts';
import ShadowCard from '../../components/blog/ShadowCard';
import MyAppBar from '../../components/MyAppBar';
import MyFooter from '../../components/MyFooter';
import styles from '../../styles/home.module.css';
import { blogs } from '../../utils/blog-data';

const DobaareBlog = () => {
  return (
    <div style={{ position: 'relative' }}>
      <Head>
        <title>مجله دوباره | Dobaare blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.polygon}></div>
      <MyAppBar />
      <Divider
        sx={{
          width: 'calc(100% + 20px)',
          zIndex: '5',
          position: 'relative',
          my: 3,
        }}
      />
      <Box sx={{ width: 'calc(100% + 20px)' }}>
        <Grid
          container
          sx={{
            px: '5%',
            zIndex: 1,
            position: 'relative',
          }}
          spacing={3}
        >
          {blogs.map((b, i) => (
            <Grid item xs={12} md={i === 0 || i === 3 ? 7 : 5} key={i}>
              <ShadowCard data={b} />
            </Grid>
          ))}
          <Grid item xs={12} md={4} sx={{ p: 2 }}>
            <PopularPosts />
          </Grid>
          <Grid item xs={12} md={8} sx={{ mt: 5 }}>
            <LatestArticles />
          </Grid>
        </Grid>
      </Box>
      <MyFooter />
    </div>
  );
};

export default DobaareBlog;
