import { Box, Typography } from '@mui/material';
import Head from 'next/head';
import MyAccordion from '../components/MyAccordion';
import MyAppBar from '../components/MyAppBar';
import MyFooter from '../components/MyFooter';
import Section1 from '../components/Section1';
import Section2 from '../components/Section2';
import Section3 from '../components/Section3';
import Section4 from '../components/Section4';
import Section5 from '../components/Section5';
import Section6 from '../components/Section6';
import Section7 from '../components/Section7';
import Section8 from '../components/Section8';
import styles from '../styles/home.module.css';
import { ScrollDownIcon } from '../utils/icons';
import Image from 'next/image';

export default function Home() {
  return (
    <div style={{ position: 'relative' }}>
      <Head>
        <title>دوباره | Dobaare</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.polygon}></div>
      <MyAppBar />
      <Section1 />
      {/* Learn more */}
      <Box
        sx={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          gap: 1.5,
          width: 'calc(100% + 20px)',
          m: '0 auto',
          position: 'relative',
          zIndex: '2',
        }}
      >
        <Typography
          sx={{
            color: 'black',
            direction: 'rtl',
            fontSize: '14px',
            fontWeight: '500',
            color: '#014351',
          }}
        >
          بیشتر بدانید...
        </Typography>
        <Image src={ScrollDownIcon} alt="scroll dow icon" />
      </Box>
      <Section2 />
      <Section3 />
      <Section4 />
      <Section5 />
      <Section6 />
      <Box sx={{ width: 'calc(100% + 20px)' }}>
        <MyAccordion />
      </Box>
      <Box sx={{ width: 'calc(100% + 20px)', mb: 6 }}>
        <Typography
          variant="h5"
          sx={{
            fontWeight: 'bold',
            textAlign: 'center',
            width: { xs: '80%', md: '70%' },
            direction: 'rtl',
            maxWidth: '700px',
            color: '#014351',
            mx: 'auto',
            my: 8,
          }}
        >
          در مجله دوباره مقالات زیر را بخوانید:
        </Typography>
      </Box>
      <Section7 />
      <Section8 />
      <MyFooter />
    </div>
  );
}
